groups.inviteUsers.label=Select Users to Invite
groups.addUsers.label=Select Users to Add
groups.inviteCLoudUsers.label=Prepare & Send Invitations
groups.invitedUsers.label=Sent Invitations
groups.inviteUsers.button.label=Invite

#Group view msg
group.view.noprofile.msg=There is no profile information for this group.
group.view.profile.heading=Profile
group.view.rename.msg=Please  enter a new name for this group
group.view.inviteMembers.heading=Invite New Members
group.edit.profile.link=Edit
group.export.link=Export LabGroup's Work
group.profile.edit.help= Please enter a short description of this group.
group.members.label=Members
group.actions.changerole=Change Role
group.labgroup.name=LabGroup
group.projectgroup.name=Project Group
group.edit.piCanEditAllCheckbox.title=PI can edit all work in this lab group
group.edit.hideGroupProfile.title=Hide the group from public listings
group.view.groupProfileHidden.msg=This group is hidden from public listings.

group.edit.mustbe1.admin.error.msg=Sorry, cannot remove the only admin or PI of \
 this group. Please assign a new admin or PI role to this group before \
 deleting this member.
group.edit.mustbe1.groupowner.error.msg=Sorry, cannot remove the only group owner \
 this group. Please assign a group owner role to this group before \
 deleting this member.
group.edit.nogroupownerdelete.error.msg=You cannot delete owner of a labgroup
group.edit.emptygrouprequired.error.msg=Other group members still exist that may want access to user's work
group.edit.invalidrolename.error.msg=Invalid role name value - must be one of \
 DEFAULT or RS_LAB_ADMIN.
group.swapPi.labGroupOny.err=Can't alter PIs of a collaboration group {0}, aborting set new PI
group.swapPi.requiredPI.role=New PI must have global PI role
group.swapPi.requiredPI.inGroup=The new PI must already belong to the group
group.swapPi.requiredNewPI=New PI must be different from old PI

# React UI messages generated by i18n extractor for src/main/webapp/ui/src/CreateGroup/CreateGroup.tsx
groups.createGroup.createGroup.createGroupText=Create group {textIconButton}
groups.createGroup.createGroup.createGroup=Create Group
groups.createGroup.createGroup.back=Back

# React UI messages generated by i18n extractor for src/main/webapp/ui/src/CreateGroup/CreateGroupStep1.tsx
groups.createGroup.createGroupStep1.groupName=Group Name
groups.createGroup.createGroupStep1.enterANameToIdentifyThe=Enter a name to identify the new group
groups.createGroup.createGroupStep1.groupNameLabel=Group Name

# React UI messages generated by i18n extractor for src/main/webapp/ui/src/CreateGroup/CreateGroupStep2.tsx
groups.createGroup.createGroupStep2.selectPi=Select PI
groups.createGroup.createGroupStep2.piRoleAriaLabel=Pi Role
groups.createGroup.createGroupStep2.makeMeTheGroupPiLabel=Make me the group PI and invite users
groups.createGroup.createGroupStep2.nominateAPiMakeMeLab=Nominate a PI, make me Lab Admin, and supply users for pending invitations.
groups.createGroup.createGroupStep2.noteGroupWontBeCreatedUntil=Note: group wont be created until PI accepts invitation
groups.createGroup.createGroupStep2.enterASingleEmailAddressOf=Enter a single email address of a new or existing user to be asked to be group PI.
groups.createGroup.createGroupStep2.startTypingPlaceholder=Start typing...
groups.createGroup.createGroupStep2.pleaseEnterAValidEmailAddress=Please enter a valid email address

# React UI messages generated by i18n extractor for src/main/webapp/ui/src/CreateGroup/CreateGroupStep3.tsx
groups.createGroup.createGroupStep3.inviteRspaceUsers=Invite RSpace users
groups.createGroup.createGroupStep3.typeAtLeast3Characters=type at least 3 characters
groups.createGroup.createGroupStep3.enterEmailAddressPlaceholder=Enter email address
groups.createGroup.createGroupStep3.inviteNewUsers=Invite new users
groups.createGroup.createGroupStep3.enterEmailAddressPlaceholder2=Enter email address
groups.createGroup.createGroupStep3.pleaseEnterAValidEmailAddress=Please enter a valid email address

# React UI messages generated by i18n extractor for src/main/webapp/ui/src/CreateGroup/CreateGroupStep4.tsx
groups.createGroup.createGroupStep4.summary=Summary
groups.createGroup.createGroupStep4.groupName=Group name:
groups.createGroup.createGroupStep4.youRequireAGroupName=You require a group name
groups.createGroup.createGroupStep4.groupOwner=Group Owner:
groups.createGroup.createGroupStep4.pi=PI:
groups.createGroup.createGroupStep4.youMustSelectAPi=You must select a PI
groups.createGroup.createGroupStep4.invitedMembers=Invited members:
groups.createGroup.createGroupStep4.invitedNonMembers=Invited non-members:
